name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: gabime/spdlog
        path: spdlog
        
    - name:  Install spdlog dependency
      shell: bash
      run: cd spdlog && mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS=-fpic -DSPDLOG_BUILD_EXAMPLE=OFF .. && sudo make -j install 
    
    - uses: actions/checkout@v2
      with:
        repository: google/leveldb
        path: leveldb
        submodules: true
        
    - name:  Install leveldb dependency
      shell: bash
      run: cd leveldb && mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS=-fpic -DLEVELDB_BUILD_TESTS=OFF -DLEVELDB_BUILD_BENCHMARKS=OFF .. && sudo make -j install 
    
    - uses: actions/checkout@v2
    
    - name : Install gtest and doxygen 
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev doxygen
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build 

    - name: Build
      run: cd build && make -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test
      
